### ISSUE TITLE
Symbol’s value as variable is void: visit

### ISSUE THREAD

**Issue by TheEccentricConnisure** [MagiFeeney/scamx#1]
### Description

**Error Message:**
```
Error (use-package): scamx/:catch: Symbol’s value as variable is void: visit
```

### Environment Information

- **Operating System:** Opensuse-TW/Linux
- **Emacs Version:** 29.2
- **Emacs Package Manager:** [elpaca](https://github.com/progfolio/elpaca)

### Steps to Reproduce

1. Install `scamx` package using the following configuration:
   ```emacs-lisp
   (use-package scamx
     :ensure (:host github :repo "MagiFeeney/scamx")
     :config
     (electric-pair-mode))
   ```

2. Attempt to run Emacs with the provided configuration.

### Expected Behavior

The `scamx` package should be loaded without any errors.

### Actual Behavior

The error mentioned above occurs, preventing the successful loading of the `scamx` package.

### Additional Information

- This issue is reproducible in the specified environment.
- No other conflicting packages are being used.

Thank you for your assistance in resolving this issue!

**Comment by MagiFeeney** [comment]
Have you personally tried this schedule?

```
git clone https://github.com/MagiFeeney/scamx.git && mv scamx ~/.emacs.d
```
And then
```
(use-package scamx
  :load-path "~/.emacs.d/scamx/"
  :config
  (electric-pair-mode))
```
It works fine for me.

**Comment by TheEccentricConnisure** [comment]
I am currently not able to do so, however, I will attempt it and provide you with a response.

**Comment by TheEccentricConnisure** [comment]
I tried to install the package again with the elpaca package manager, and it turned out that the ":demand t" was missing in my installation. After deleting the meow and the scamx packages, it went on to install smoothly.

So the final code block was: `

`` 
(use-package scamx 
    :ensure (:host github :repo "MagiFeeney/scamx")
    :after (meow)
    :demand t
    :config
    (electric-pair-mode))
`

**Comment by nadako** [comment]
I'm now getting a similar error `Symbol’s value as variable is void: converSymbol’s value as variable is void: convert` when installed with package vc:

```elisp
(use-package scamx
  :ensure t
  :vc (:url "https://github.com/MagiFeeney/scamx/")
  :after (meow multiple-cursors)
  :demand t
  )
```

worked just fine with manual clone and load-path. am i missing something?

**Comment by MagiFeeney** [comment]
From my test, it seems that the keyword :after doesn't install meow, which leads to scamx unable to function normally.
